#!/usr/bin/env ruby
require 'tile_editor'
if ARGV.size > 0
  tile_set_name = ARGV.shift
else
  tile_set_name = 'Original-Carcassonne-Classic'
end
config = {
  :tile_set_name => tile_set_name,
  :board_max_tiles_x => 5,
  :board_max_tiles_y => 6,
}

@tile_editor = TileEditor.new("caRcassonne Tile Editor",config)
puts "defined grid as #{@tile_editor.grid.max_x} by #{@tile_editor.grid.max_y}"
@tile_editor.show
